[build]
  command = "echo 'No build command needed for static site'"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Environment variables should be set in Netlify UI:
# OPENAI_API_KEY = "your-openai-api-key"
# QDRANT_URL = "your-qdrant-url"  
# QDRANT_API_KEY = "your-qdrant-api-key"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"